### ISSUE TITLE
Pre-Trained Model

### ISSUE THREAD

**Issue by dragonlee258079** [MehmetAygun/demistfy_correspondence#2]
Hi, I couldn't find your pre-trained model, only log files are provided, but loading log files can only load the last convolutional layer of the model.

**Comment by MehmetAygun** [comment]
Hi,

In all of our experiments the backbones are frozen, so we just used already pre-trained versions. We only trained one single convolutional layer, and the provided files have the weights for them.

**Comment by dragonlee258079** [comment]
Hi, the last layer of the resnet50 network outputs features of 2048 channels, but the corresponding files only provided 1024 to 256 convolutional layer, and there is no model construction for this convolutional layer in the code.

**Comment by MehmetAygun** [comment]
Sorry my bad, the projection layer (single layer conv) is coded as the parameter w in the evaluation code, 
https://github.com/MehmetAygun/demistfy_correspondence/blob/main/evaluation/cub/evaluate.py#L29

Here you can see it is loaded: https://github.com/MehmetAygun/demistfy_correspondence/blob/main/evaluation/cub/evaluate.py#L144C42-L144C42

The model that you are trying might be the unsupervised Resnet model which has a different output feature dimension.

**Comment by dragonlee258079** [comment]
Thank you for resolving my question.
